### ISSUE TITLE
Number of user in shakespeare dataset 

### ISSUE THREAD

**Issue by qjing666** [TalwalkarLab/leaf#17]
I run the command: bash preprocess.sh -s niid --sf 1.0 -k 0 -t sample -tf 0.8 under the shakespeare dataset and visualize the number of users in the training data set, the number I get is 1129 which does not match the statistics in the README file(2288 users).

**Comment by ZhicongLiang** [comment]
I got the same issue!

**Comment by scaldas** [comment]
Sorry, this is due to mutating source data + us skipping roles with less than two lines (as we need at least one line for training and one for testing). We will be updating the documentation soon.
